spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8001
management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway Service
    description: Gateway microservice
    version: 1.0.0
